import React from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, Calculator, Check, ChevronDown, PackageCheck, Plus, Search, X } from 'lucide-react';
import { supabase } from '../lib/supabaseClient';
import { getExchangeRates, type ExchangeRatesResult, type SupportedCurrency } from '../lib/exchangeRates';
import { calculateImportEstimate, type ImportEstimateInput } from './importCosting';
import './importCosting.css';

type Props={onNavigate:(path:string)=>void;organizationId:string};
type Estimate={id:string;reference_number:string;client_name:string;supplier:string;part_number:string;item_description:string;country:string;international_freight:number;shipment_weight_kg:number|null;freight_mode:string|null;total_cost:number;recommended_unit_price:number;profit_loss:number;result:'PROFIT'|'BREAK-EVEN'|'LOSS';status:string;created_at:string};
type Form=Record<keyof ImportEstimateInput,string>&{carrier:string;customsEntryNumber:string;customsOffice:string;financingMonthlyPercent:string;tariffFraction:string;incoterm:string;shipmentWeightKg:string;freightMode:string;freightRateSource:string;freightBaseCharge:string;freightRatePerKg:string;originCity:string;originPostalCode:string;destinationCity:string;destinationPostalCode:string;packageLengthCm:string;packageWidthCm:string;packageHeightCm:string};
const zeroCosts={internationalFreight:'0',insurance:'0',taxes:'0',customsAgentFees:'0',handling:'0',domesticTransport:'0',otherExpenses:'0',logisticsManagement:'0'};
const blank:Form={clientName:'',supplier:'',partNumber:'',description:'',quantity:'1',country:'Germany',operationType:'Purchase',purchaseCurrency:'USD',invoiceUnitValue:'',purchaseFx:'',saleCurrency:'USD',clientUnitPrice:'',saleFx:'',desiredMarginPercent:'15',...zeroCosts,carrier:'',customsEntryNumber:'',customsOffice:'AICM',financingMonthlyPercent:'0.065',tariffFraction:'',incoterm:'',shipmentWeightKg:'',freightMode:'Air',freightRateSource:'',freightBaseCharge:'',freightRatePerKg:'',originCity:'',originPostalCode:'',destinationCity:'',destinationPostalCode:'',packageLengthCm:'',packageWidthCm:'',packageHeightCm:''};
const numberKeys:Array<keyof ImportEstimateInput>=['quantity','invoiceUnitValue','purchaseFx','clientUnitPrice','saleFx','desiredMarginPercent','internationalFreight','insurance','taxes','customsAgentFees','handling','domesticTransport','otherExpenses','logisticsManagement'];
type DropdownOption={value:string;label:string;description?:string};
const currencyOptions=['USD','EUR','MXN'].map(value=>({value,label:value}));
const countryOptions=['Germany','USA','Japan','China','Brazil','Other'].map(value=>({value,label:value}));
const operationOptions=[{value:'Purchase',label:'Purchase'},{value:'Repair',label:'Repair'},{value:'Resharpening',label:'Resharpening'},{value:'Warranty',label:'Warranty'},{value:'Intercompany',label:'Intercompany'}];
const incotermOptions:DropdownOption[]=[
  {value:'EXW',label:'EXW · Ex Works',description:'Buyer assumes transportation, export, import and delivery costs from the seller facility.'},
  {value:'FCA',label:'FCA · Free Carrier',description:'Seller clears export and delivers the goods to the buyer-appointed carrier.'},
  {value:'FOB',label:'FOB · Free on Board',description:'Seller covers costs until goods are loaded aboard the vessel at origin.'},
  {value:'CIF',label:'CIF · Cost, Insurance & Freight',description:'Seller includes ocean freight and insurance to the destination port; import costs remain with buyer.'},
  {value:'DAP',label:'DAP · Delivered at Place',description:'Seller delivers to the agreed place; buyer handles import clearance and duties.'},
  {value:'DDP',label:'DDP · Delivered Duty Paid',description:'Seller covers delivery and import duties. Validate carefully to avoid duplicating freight, insurance or taxes.'},
];
const carrierOptions=['Dachser','UPS','DHL','Estafeta','Other'].map(value=>({value,label:value}));
const customsOptions=['AIFA','AICM','Laredo','Qro','Other'].map(value=>({value,label:value}));
const freightModeOptions=[{value:'Air',label:'Air freight',description:'Faster preliminary estimate using an origin-based rate per kilogram.'},{value:'Ground',label:'Ground freight',description:'Planning estimate for routes where ground transportation is feasible.'},{value:'Ocean',label:'Ocean freight',description:'Preliminary consolidated-cargo estimate; final pricing requires volume and port details.'}];
const mxn=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'MXN'}).format(value);
const unit=(value:number,currency:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency||'USD'}).format(value);
const parseNumber=(value:string)=>Number(value.replace(/,/g,''))||0;
const formatMoney=(value:string)=>value===''?'':new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(parseNumber(value));

function Field({label,children,className='' }:{label:string;children:React.ReactNode;className?:string}){return <label className={`import-cost-field ${className}`.trim()}><span>{label}</span>{children}</label>}
function MoneyInput({value,currency,onChange,readOnly=false}:{value:string;currency:string;onChange:(value:string)=>void;readOnly?:boolean}){return <div className="import-money-input"><span>{currency}</span><input inputMode="decimal" readOnly={readOnly} aria-readonly={readOnly} value={readOnly?formatMoney(value):value} onFocus={event=>{if(!readOnly)onChange(event.currentTarget.value.replace(/,/g,''))}} onBlur={event=>{if(!readOnly)onChange(formatMoney(event.currentTarget.value))}} onChange={event=>{if(!readOnly&&/^[\d,]*\.?\d*$/.test(event.target.value))onChange(event.target.value)}}/></div>}
function ImportDropdown({value,options,placeholder,onChange}:{value:string;options:DropdownOption[];placeholder:string;onChange:(value:string)=>void}){
  const[open,setOpen]=React.useState(false),[position,setPosition]=React.useState<React.CSSProperties|null>(null);const selected=options.find(option=>option.value===value);const triggerRef=React.useRef<HTMLDivElement>(null),menuRef=React.useRef<HTMLDivElement>(null);
  const updatePosition=React.useCallback(()=>{const rect=triggerRef.current?.getBoundingClientRect();if(!rect)return;const margin=10,gap=5,desired=Math.min(280,options.length*58+10),below=window.innerHeight-rect.bottom-margin-gap,above=rect.top-margin-gap,up=below<Math.min(180,desired)&&above>below,maxHeight=Math.max(80,Math.min(desired,up?above:below)),width=Math.min(rect.width,window.innerWidth-margin*2),left=Math.max(margin,Math.min(rect.left,window.innerWidth-width-margin));setPosition({position:'fixed',left,top:up?Math.max(margin,rect.top-gap-maxHeight):rect.bottom+gap,width,maxHeight})},[options.length]);
  React.useLayoutEffect(()=>{if(open)updatePosition()},[open,updatePosition]);
  React.useEffect(()=>{if(!open)return;const outside=(event:MouseEvent)=>{const target=event.target as Node;if(!triggerRef.current?.contains(target)&&!menuRef.current?.contains(target))setOpen(false)},reposition=()=>updatePosition();document.addEventListener('mousedown',outside);window.addEventListener('resize',reposition);window.addEventListener('scroll',reposition,true);return()=>{document.removeEventListener('mousedown',outside);window.removeEventListener('resize',reposition);window.removeEventListener('scroll',reposition,true)}},[open,updatePosition]);
  const menu=open&&position&&typeof document!=='undefined'?createPortal(<div ref={menuRef} className="import-cost-dropdown-menu portal" style={position} role="listbox">{options.length?options.map(option=><button type="button" role="option" aria-selected={option.value===value} className={option.value===value?'selected':''} key={option.value} onClick={()=>{onChange(option.value);setOpen(false)}}><span><strong>{option.label}</strong>{option.description?<small>{option.description}</small>:null}</span>{option.value===value?<Check size={15}/>:null}</button>):<p>No registered options available.</p>}</div>,document.body):null;
  return <div ref={triggerRef} className={`import-cost-dropdown${open?' open':''}`}><button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)}><span className={selected?'':'placeholder'}>{selected?.label??placeholder}</span><ChevronDown size={16}/></button>{menu}</div>
}
function Step({number,title,description,children,className='' }:{number:string;title:string;description:string;children:React.ReactNode;className?:string}){return <section className={`import-cost-step ${className}`.trim()}><header><b>Step {number}</b><span><strong>{title}</strong><small>{description}</small></span><em>Required</em></header><div>{children}</div></section>}
function ExchangeRateField({label,currency,value,info,loading,error}:{label:string;currency:string;value:string;info?:ExchangeRatesResult;loading:boolean;error:string}){return <Field label={label}><div className="import-exchange-rate"><input readOnly aria-readonly="true" value={loading?'Loading…':value}/><small>{error||(!info?'Waiting for current rate…':`Frankfurter · Market date ${info.date} · Retrieved ${new Date(info.fetchedAt).toLocaleString()}${info.fromCache?' · cached':''}${info.stale?' · stale fallback':''}`)}</small><em>1 {currency} = {value||'—'} MXN</em></div></Field>}

export function ImportCostingWorkspace({onNavigate,organizationId}:Props){
  const [records,setRecords]=React.useState<Estimate[]>([]),[clientOptions,setClientOptions]=React.useState<DropdownOption[]>([]),[supplierOptions,setSupplierOptions]=React.useState<DropdownOption[]>([]),[form,setForm]=React.useState<Form>(blank),[open,setOpen]=React.useState(false),[search,setSearch]=React.useState(''),[loading,setLoading]=React.useState(true),[saving,setSaving]=React.useState(false),[message,setMessage]=React.useState('');
  const [rateInfo,setRateInfo]=React.useState<{purchase?:ExchangeRatesResult;sale?:ExchangeRatesResult}>({}),[ratesLoading,setRatesLoading]=React.useState(false),[rateError,setRateError]=React.useState('');
  const [freightExplanation,setFreightExplanation]=React.useState(''),[freightApiLoading,setFreightApiLoading]=React.useState(false);
  const load=React.useCallback(async()=>{setLoading(true);const[estimateResult,clientResult,supplierResult]=await Promise.all([supabase.from('mes_import_cost_estimates').select('id,reference_number,client_name,supplier,part_number,item_description,country,international_freight,shipment_weight_kg,freight_mode,total_cost,recommended_unit_price,profit_loss,result,status,created_at').eq('organization_id',organizationId).order('created_at',{ascending:false}),supabase.from('mes_customers').select('id,customer_name').eq('organization_id',organizationId).eq('status','active').order('customer_name'),supabase.from('mes_suppliers').select('id,name').eq('organization_id',organizationId).order('name')]);if(estimateResult.error)setMessage(`Unable to load import estimates: ${estimateResult.error.message}. Apply SQL migration 100.`);else{setRecords((estimateResult.data??[]) as Estimate[]);setMessage('')}if(clientResult.error)setMessage(current=>current||`Unable to load clients: ${clientResult.error.message}`);else setClientOptions((clientResult.data??[]).map(client=>({value:String(client.customer_name),label:String(client.customer_name)})));if(supplierResult.error)setMessage(current=>current||`Unable to load suppliers: ${supplierResult.error.message}`);else setSupplierOptions((supplierResult.data??[]).map(supplier=>({value:String(supplier.name),label:String(supplier.name)})));setLoading(false)},[organizationId]);
  React.useEffect(()=>{void load()},[load]);
  React.useEffect(()=>{if(!open)return;let active=true;setRatesLoading(true);setRateError('');Promise.all([getExchangeRates(form.purchaseCurrency as SupportedCurrency,['MXN']),getExchangeRates(form.saleCurrency as SupportedCurrency,['MXN'])]).then(([purchase,sale])=>{if(!active)return;const purchaseRate=purchase.rates.MXN??(form.purchaseCurrency==='MXN'?1:0),saleRate=sale.rates.MXN??(form.saleCurrency==='MXN'?1:0);setRateInfo({purchase,sale});setForm(current=>({...current,purchaseFx:String(purchaseRate),saleFx:String(saleRate)}))}).catch(error=>{if(active)setRateError(error instanceof Error?error.message:'Unable to load exchange rates.')}).finally(()=>{if(active)setRatesLoading(false)});return()=>{active=false}},[open,form.purchaseCurrency,form.saleCurrency]);
  const values=Object.fromEntries(numberKeys.map(key=>[key,parseNumber(form[key])])) as unknown as Pick<ImportEstimateInput,typeof numberKeys[number]>;
  const input:ImportEstimateInput={clientName:form.clientName,supplier:form.supplier,partNumber:form.partNumber,description:form.description,country:form.country,operationType:form.operationType,purchaseCurrency:form.purchaseCurrency,saleCurrency:form.saleCurrency,...values};
  const totals=calculateImportEstimate(input);
  React.useEffect(()=>{const merchandise=values.quantity*values.invoiceUnitValue*values.purchaseFx;const iva=Math.round(merchandise*.16*100)/100;setForm(current=>current.taxes===String(iva)?current:{...current,taxes:String(iva)})},[values.quantity,values.invoiceUnitValue,values.purchaseFx]);
  const nextReference=`IMP-${new Date().getFullYear()}-${String(Math.max(0,...records.map(record=>Number(record.reference_number.match(/(\d+)$/)?.[1])||0))+1).padStart(4,'0')}`;
  const valid=Boolean(form.clientName.trim()&&form.supplier.trim()&&form.partNumber.trim()&&form.description.trim()&&values.quantity>0&&values.purchaseFx>0&&values.saleFx>0&&form.invoiceUnitValue!==''&&form.clientUnitPrice!=='');
  const update=(key:keyof Form,value:string)=>setForm(current=>({...current,[key]:value}));
  const estimateFreight=()=>{const weight=parseNumber(form.shipmentWeightKg);if(!(weight>0)){setFreightExplanation('Enter the total shipment weight to estimate freight.');return}const usable=records.filter(record=>Number(record.shipment_weight_kg)>0&&Number(record.international_freight)>0);const exact=usable.filter(record=>record.country===form.country&&record.freight_mode===form.freightMode),sameMode=usable.filter(record=>record.freight_mode===form.freightMode);const samples=exact.length?exact:sameMode.length?sameMode:usable;if(!samples.length){setFreightExplanation('No YVIMO freight history with both confirmed weight and freight amount is available yet. Enter the carrier amount manually; after it is saved, future estimates can use it as a documented benchmark.');return}const rates=samples.map(record=>Number(record.international_freight)/Number(record.shipment_weight_kg)).sort((a,b)=>a-b),middle=Math.floor(rates.length/2),median=rates.length%2?rates[middle]:(rates[middle-1]+rates[middle])/2,amount=Math.round(weight*median*100)/100,scope=exact.length?`${form.country} + ${form.freightMode}`:sameMode.length?`${form.freightMode} across all origins`:'all available origins and modes';update('internationalFreight',formatMoney(String(amount)));update('freightRateSource',`YVIMO historical median · ${scope}`);update('freightBaseCharge','0');update('freightRatePerKg',String(median));setFreightExplanation(`Source: YVIMO import history (${samples.length} record${samples.length===1?'':'s'}, ${scope}). The median observed rate is ${mxn(median)}/kg. Calculation: ${weight.toFixed(2)} kg × ${mxn(median)}/kg = ${mxn(amount)}. This is a planning estimate, not a live carrier quote; replace it if a formal quote is available.`)};
  const estimateFreightApi=async()=>{const weight=parseNumber(form.shipmentWeightKg),length=parseNumber(form.packageLengthCm),width=parseNumber(form.packageWidthCm),height=parseNumber(form.packageHeightCm);if(!(weight>0&&length>0&&width>0&&height>0&&form.originCity.trim()&&form.originPostalCode.trim()&&form.destinationCity.trim()&&form.destinationPostalCode.trim())){setFreightExplanation('Complete origin city/postal code, destination city/postal code, package dimensions and weight before requesting a live API estimate.');return}setFreightApiLoading(true);setFreightExplanation('Requesting available carrier rates through EasyPost…');const{data,error}=await supabase.functions.invoke('freight-rate-estimate',{body:{origin:{country:form.country,city:form.originCity.trim(),postalCode:form.originPostalCode.trim()},destination:{country:'Mexico',city:form.destinationCity.trim(),postalCode:form.destinationPostalCode.trim()},parcel:{weightKg:weight,lengthCm:length,widthCm:width,heightCm:height},customs:{description:form.description||form.partNumber,quantity:values.quantity,value:values.invoiceUnitValue*values.quantity,currency:form.purchaseCurrency,tariffCode:form.tariffFraction||undefined}}});setFreightApiLoading(false);if(error||!data?.amountMxn){setFreightExplanation(`EasyPost API estimate unavailable: ${error?.message||data?.error||'No eligible carrier returned a rate.'} Verify the route, package data and the EASYPOST_API_KEY configured in Supabase.`);return}update('internationalFreight',formatMoney(String(data.amountMxn)));update('freightRateSource',`${data.provider} · ${data.carrier} ${data.service}`);update('freightBaseCharge',String(data.amountMxn));update('freightRatePerKg',String(data.amountMxn/weight));setFreightExplanation(`Source: live ${data.provider} rate returned by ${data.carrier} (${data.service}) at ${new Date(data.quotedAt).toLocaleString()}. Carrier amount: ${data.originalCurrency} ${Number(data.originalAmount).toFixed(2)}; converted at 1 ${data.originalCurrency} = ${Number(data.exchangeRate).toFixed(6)} MXN (${data.exchangeRateDate}) for an estimated total of ${mxn(Number(data.amountMxn))}. The API used route, actual weight and package dimensions; duties and taxes are excluded unless the carrier explicitly includes them.`)};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!valid)return;setSaving(true);setMessage('');const payload={organization_id:organizationId,reference_number:nextReference,client_name:form.clientName.trim(),supplier:form.supplier.trim(),part_number:form.partNumber.trim(),item_description:form.description.trim(),quantity:values.quantity,country:form.country,operation_type:form.operationType,purchase_currency:form.purchaseCurrency,invoice_unit_value:values.invoiceUnitValue,purchase_fx:values.purchaseFx,sale_currency:form.saleCurrency,client_unit_price:values.clientUnitPrice,sale_fx:values.saleFx,desired_margin_percent:values.desiredMarginPercent,international_freight:values.internationalFreight,insurance:values.insurance,taxes:values.taxes,customs_agent_fees:values.customsAgentFees,handling:values.handling,domestic_transport:values.domesticTransport,other_expenses:values.otherExpenses,logistics_management:values.logisticsManagement,shipment_weight_kg:parseNumber(form.shipmentWeightKg)||null,freight_mode:form.freightMode||null,freight_rate_source:form.freightRateSource||null,freight_base_charge:parseNumber(form.freightBaseCharge)||null,freight_rate_per_kg:parseNumber(form.freightRatePerKg)||null,origin_city:form.originCity||null,origin_postal_code:form.originPostalCode||null,destination_city:form.destinationCity||null,destination_postal_code:form.destinationPostalCode||null,package_length_cm:parseNumber(form.packageLengthCm)||null,package_width_cm:parseNumber(form.packageWidthCm)||null,package_height_cm:parseNumber(form.packageHeightCm)||null,carrier:form.carrier||null,customs_entry_number:form.customsEntryNumber||null,customs_office:form.customsOffice||null,financing_monthly_percent:Number(form.financingMonthlyPercent)||0,tariff_fraction:form.tariffFraction||null,incoterm:form.incoterm||null,merchandise_cost:totals.merchandiseCost,logistics_cost:totals.logisticsCost,total_cost:totals.totalCost,client_sale:totals.clientSale,profit_loss:totals.profitLoss,minimum_unit_price:totals.minimumUnitPrice,recommended_unit_price:totals.recommendedUnitPrice,result:totals.result,status:'draft'};const{error}=await supabase.from('mes_import_cost_estimates').insert(payload);setSaving(false);if(error){setMessage(error.message);return}setOpen(false);setForm(blank);setFreightExplanation('');await load()};
  const filtered=records.filter(record=>`${record.reference_number} ${record.client_name} ${record.supplier} ${record.part_number} ${record.item_description} ${record.country} ${record.status}`.toLowerCase().includes(search.toLowerCase()));
  const logistics=[['Insurance','insurance'],['Customs agent fees','customsAgentFees'],['Handling','handling'],['Domestic transport','domesticTransport'],['Other expenses','otherExpenses'],['Logistics management','logisticsManagement']] as const;
  return <section className="mes-workspace-panel import-costing-workspace"><div className="mes-screen-header"><button className="academy-back-button engineering-back-button mes-workspace-back" type="button" onClick={()=>onNavigate('/workspace/manufacturing-ops/intelligence')}><ArrowLeft size={16}/> Ops Intelligence</button><div className="mes-workspace-heading"><p className="eyebrow">OPS INTELLIGENCE / IMPORT COSTING</p><h2>Import Costing</h2><p>Calculate landed import costs, protect commercial margin, and maintain a traceable history of every customer import offer.</p></div></div>
    <div className="import-cost-toolbar"><button type="button" onClick={()=>{setForm(blank);setOpen(true)}}><Plus size={18}/> New Import Estimate</button><label><span>Search import history</span><div><Search size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Reference, client, supplier, part, country"/></div></label></div>
    {message?<div className="quotations-message">{message}</div>:null}
    <section className="import-cost-register"><header><div><span>Import register</span><strong>Cost estimates and customer offers</strong></div><b>{filtered.length} showing / {records.length} total</b></header><div className="import-cost-table"><div className="head"><span>Reference</span><span>Client</span><span>Supplier / Part</span><span>Total landed cost</span><span>Recommended unit</span><span>Profit / loss</span><span>Status</span></div>{loading?<p>Loading import history…</p>:filtered.length?filtered.map(record=><div className="row" key={record.id}><strong>{record.reference_number}</strong><span>{record.client_name}</span><span><b>{record.supplier}</b><small>{record.part_number} · {record.item_description}</small></span><span>{mxn(record.total_cost)}</span><span>{unit(record.recommended_unit_price,'USD')}</span><span className={record.profit_loss<-.005?'loss':record.profit_loss>.005?'profit':'neutral'}>{mxn(record.profit_loss)}</span><em className={record.result==='LOSS'?'loss':record.result==='PROFIT'?'profit':'neutral'}>{record.result}</em></div>):<div className="empty"><PackageCheck size={30}/><strong>No import estimates yet</strong><span>Create the first estimate to start the organization history.</span></div>}</div></section>
    {open?<div className="quotation-modal-backdrop import-cost-modal-backdrop"><section className="quotation-modal import-cost-modal"><header><div><span>Import cost builder</span><h3>New Import Estimate · {nextReference}</h3><p>Build the landed cost and validate the customer selling price before offering the import.</p></div><button type="button" onClick={()=>setOpen(false)}><X size={20}/></button></header><form onSubmit={save}><main><Step className="import-operation-step" number="01" title="Identify the operation" description="Customer, supplier, item and import context."><Field className="client" label="Client"><ImportDropdown value={form.clientName} options={clientOptions} placeholder="Select registered client" onChange={value=>update('clientName',value)}/></Field><Field className="supplier" label="Supplier"><ImportDropdown value={form.supplier} options={supplierOptions} placeholder="Select registered supplier" onChange={value=>update('supplier',value)}/></Field><Field className="part" label="Part number"><input value={form.partNumber} onChange={e=>update('partNumber',e.target.value)}/></Field><Field className="description" label="Item description"><input value={form.description} onChange={e=>update('description',e.target.value)}/></Field><Field className="quantity" label="Quantity"><input min="0.0001" step="0.0001" type="number" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></Field><Field className="country" label="Country"><ImportDropdown value={form.country} options={countryOptions} placeholder="Select country" onChange={value=>update('country',value)}/></Field><Field className="operation" label="Operation type"><ImportDropdown value={form.operationType} options={operationOptions} placeholder="Select operation" onChange={value=>update('operationType',value)}/></Field><Field className="incoterm" label="Incoterm"><ImportDropdown value={form.incoterm} options={incotermOptions} placeholder="Select Incoterm" onChange={value=>update('incoterm',value)}/></Field></Step>
      <Step number="02" title="Set purchase and customer pricing" description="Currencies, automatic exchange rates, selling price and target margin."><Field label="Purchase currency"><ImportDropdown value={form.purchaseCurrency} options={currencyOptions} placeholder="Select currency" onChange={value=>update('purchaseCurrency',value)}/></Field><Field label="Invoice unit value"><MoneyInput currency={form.purchaseCurrency} value={form.invoiceUnitValue} onChange={value=>update('invoiceUnitValue',value)}/></Field><ExchangeRateField label="Purchase Exchange Rate to MXN" currency={form.purchaseCurrency} value={form.purchaseFx} info={rateInfo.purchase} loading={ratesLoading} error={rateError}/><Field label="Sale currency"><ImportDropdown value={form.saleCurrency} options={currencyOptions} placeholder="Select currency" onChange={value=>update('saleCurrency',value)}/></Field><Field label="Customer unit price"><MoneyInput currency={form.saleCurrency} value={form.clientUnitPrice} onChange={value=>update('clientUnitPrice',value)}/></Field><ExchangeRateField label="Sale Exchange Rate to MXN" currency={form.saleCurrency} value={form.saleFx} info={rateInfo.sale} loading={ratesLoading} error={rateError}/><Field label="Desired margin %"><input min="0" step="0.01" type="number" value={form.desiredMarginPercent} onChange={e=>update('desiredMarginPercent',e.target.value)}/></Field></Step>
      <Step className="import-logistics-step" number="03" title="Add logistics and customs costs" description="All values in MXN; avoid duplicating costs already included by the Incoterm."><Field label="Freight mode"><ImportDropdown value={form.freightMode} options={freightModeOptions} placeholder="Select freight mode" onChange={value=>{update('freightMode',value);setFreightExplanation('')}}/></Field><Field label="Total shipment weight (kg)"><input min="0" step="0.01" type="number" value={form.shipmentWeightKg} onChange={e=>{update('shipmentWeightKg',e.target.value);setFreightExplanation('')}}/></Field><div className="import-api-parameters"><header><strong>API shipment parameters</strong><small>Required only for a live carrier estimate. Destination country is Mexico.</small></header><Field label="Origin city"><input value={form.originCity} onChange={e=>update('originCity',e.target.value)}/></Field><Field label="Origin postal code"><input value={form.originPostalCode} onChange={e=>update('originPostalCode',e.target.value)}/></Field><Field label="Destination city"><input value={form.destinationCity} onChange={e=>update('destinationCity',e.target.value)}/></Field><Field label="Destination postal code"><input value={form.destinationPostalCode} onChange={e=>update('destinationPostalCode',e.target.value)}/></Field><Field label="Package length (cm)"><input min="0" step="0.1" type="number" value={form.packageLengthCm} onChange={e=>update('packageLengthCm',e.target.value)}/></Field><Field label="Package width (cm)"><input min="0" step="0.1" type="number" value={form.packageWidthCm} onChange={e=>update('packageWidthCm',e.target.value)}/></Field><Field label="Package height (cm)"><input min="0" step="0.1" type="number" value={form.packageHeightCm} onChange={e=>update('packageHeightCm',e.target.value)}/></Field></div><Field className="freight" label="International freight"><div className="import-estimate-input"><MoneyInput currency="MXN" value={form.internationalFreight} onChange={value=>{update('internationalFreight',value);setFreightExplanation('Manual freight amount entered.')}}/><button type="button" onClick={estimateFreight}>Estimate with history</button><button className="api" disabled={freightApiLoading} type="button" onClick={()=>void estimateFreightApi()}>{freightApiLoading?'Estimating…':'Estimate with API'}</button></div></Field><Field className="taxes" label="Taxes (IVA 16%)"><MoneyInput readOnly currency="MXN" value={form.taxes} onChange={()=>{}}/><small className="import-calculation-note">Automatically calculated as 16% of merchandise value: quantity × invoice unit value × purchase exchange rate.</small></Field>{logistics.map(([label,key])=><Field label={label} key={key}><MoneyInput currency="MXN" value={form[key]} onChange={value=>update(key,value)}/></Field>)}</Step>
      <Step number="04" title="Complete customs traceability" description="Operational references used for review and historical analysis."><Field label="Carrier"><ImportDropdown value={form.carrier} options={carrierOptions} placeholder="Select carrier" onChange={value=>update('carrier',value)}/></Field><Field label="Customs entry number"><input value={form.customsEntryNumber} onChange={e=>update('customsEntryNumber',e.target.value)}/></Field><Field label="Customs office"><ImportDropdown value={form.customsOffice} options={customsOptions} placeholder="Select customs office" onChange={value=>update('customsOffice',value)}/></Field><Field label="Monthly financing %"><input min="0" step="0.001" type="number" value={form.financingMonthlyPercent} onChange={e=>update('financingMonthlyPercent',e.target.value)}/></Field><Field label="Tariff fraction"><input value={form.tariffFraction} onChange={e=>update('tariffFraction',e.target.value)}/></Field></Step></main>
      <aside className="import-cost-calculation"><div><Calculator size={22}/><strong>Import calculation</strong></div><dl><dt>Merchandise cost</dt><dd>{mxn(totals.merchandiseCost)}</dd><dt>Logistics cost</dt><dd>{mxn(totals.logisticsCost)}</dd><dt>Total landed cost</dt><dd>{mxn(totals.totalCost)}</dd><dt>Customer sale</dt><dd>{mxn(totals.clientSale)}</dd><dt>Profit / loss</dt><dd className={totals.result==='LOSS'?'loss':totals.result==='PROFIT'?'profit':'neutral'}>{mxn(totals.profitLoss)}</dd><dt>Minimum unit price</dt><dd>{unit(totals.minimumUnitPrice,form.saleCurrency)}</dd><dt>Recommended unit price</dt><dd>{unit(totals.recommendedUnitPrice,form.saleCurrency)}</dd><dt>Result</dt><dd className={totals.result==='LOSS'?'loss':totals.result==='PROFIT'?'profit':'neutral'}>{totals.result}</dd></dl>{form.incoterm?<section className="import-calculation-disclaimer"><b>Incoterm · {form.incoterm}</b><span>{incotermOptions.find(option=>option.value===form.incoterm)?.description}</span></section>:null}{freightExplanation?<section className="import-calculation-disclaimer"><b>Freight estimate source</b><span>{freightExplanation}</span></section>:null}</aside><footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="save" disabled={!valid||saving||ratesLoading}>{saving?'Saving…':ratesLoading?'Loading rates…':'Create Import Estimate'}</button></footer></form></section></div>:null}
  </section>;
}
