import type { ProductionOrder, Supplier, SupplierTransfer, TraceabilityEvent, WorkCenter } from './mesTypes';

export const mockWorkCenters: WorkCenter[] = [
  {
    id: 'wc-robot-01',
    code: 'RB-01',
    name: 'Robot Weld Cell 01',
    type: 'Robotic welding cell',
    status: 'running',
    currentOrder: 'MO-24018',
    capacityPerHour: 42,
    location: 'Line A / Bay 2',
    lastActivity: 'Production reported 18 min ago',
  },
  {
    id: 'wc-cnc-03',
    code: 'CNC-03',
    name: 'CNC Machining Center 03',
    type: 'Machining center',
    status: 'available',
    currentOrder: null,
    capacityPerHour: 28,
    location: 'Machining / Cell 3',
    lastActivity: 'Order MO-24015 completed 46 min ago',
  },
  {
    id: 'wc-assy-02',
    code: 'ASY-02',
    name: 'Final Assembly Station 02',
    type: 'Manual assembly',
    status: 'running',
    currentOrder: 'MO-24021',
    capacityPerHour: 65,
    location: 'Assembly / Line B',
    lastActivity: 'Operator login 9 min ago',
  },
  {
    id: 'wc-test-01',
    code: 'TST-01',
    name: 'End-of-Line Test Stand',
    type: 'Functional test',
    status: 'maintenance',
    currentOrder: null,
    capacityPerHour: 36,
    location: 'Quality / Test Area',
    lastActivity: 'Preventive maintenance started 32 min ago',
  },
  {
    id: 'wc-pack-01',
    code: 'PKG-01',
    name: 'Packaging Cell 01',
    type: 'Packaging',
    status: 'offline',
    currentOrder: null,
    capacityPerHour: 90,
    location: 'Shipping / Dock 1',
    lastActivity: 'Offline after shift close',
  },
  {
    id: 'wc-press-04',
    code: 'PRS-04',
    name: 'Hydraulic Press 04',
    type: 'Forming press',
    status: 'down',
    currentOrder: 'MO-24022',
    capacityPerHour: 54,
    location: 'Stamping / Bay 4',
    lastActivity: 'Downtime reason: sensor fault',
  },
];

export const mockProductionOrders: ProductionOrder[] = [
  {
    id: 'po-24018',
    orderNumber: 'MO-24018',
    partNumber: 'YW-1482-A',
    partName: 'Welded actuator bracket',
    plannedQuantity: 1200,
    completedQuantity: 684,
    scrapQuantity: 11,
    status: 'running',
    priority: 'high',
    dueDate: '2026-06-04',
    assignedWorkCenter: 'RB-01',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24021',
    orderNumber: 'MO-24021',
    partNumber: 'YA-3309-C',
    partName: 'Valve manifold assembly',
    plannedQuantity: 500,
    completedQuantity: 216,
    scrapQuantity: 3,
    status: 'running',
    priority: 'expedite',
    dueDate: '2026-06-02',
    assignedWorkCenter: 'ASY-02',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24022',
    orderNumber: 'MO-24022',
    partNumber: 'YP-2201-B',
    partName: 'Pressed motor cover',
    plannedQuantity: 900,
    completedQuantity: 102,
    scrapQuantity: 18,
    status: 'paused',
    priority: 'normal',
    dueDate: '2026-06-07',
    assignedWorkCenter: 'PRS-04',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24024',
    orderNumber: 'MO-24024',
    partNumber: 'YC-9004-D',
    partName: 'Control enclosure kit',
    plannedQuantity: 180,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'released',
    priority: 'normal',
    dueDate: '2026-06-10',
    assignedWorkCenter: 'CNC-03',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24025',
    orderNumber: 'MO-24025',
    partNumber: 'YT-5110-A',
    partName: 'Tested harness set',
    plannedQuantity: 320,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'planned',
    priority: 'low',
    dueDate: '2026-06-14',
    assignedWorkCenter: 'TST-01',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24026',
    orderNumber: 'MO-24026',
    partNumber: 'YH-1840-B',
    partName: 'Hydraulic clamp body',
    plannedQuantity: 640,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'released',
    priority: 'high',
    dueDate: '2026-06-06',
    assignedWorkCenter: 'CNC-03',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24027',
    orderNumber: 'MO-24027',
    partNumber: 'YS-4108-A',
    partName: 'Sensor mounting rail',
    plannedQuantity: 1100,
    completedQuantity: 928,
    scrapQuantity: 7,
    status: 'running',
    priority: 'normal',
    dueDate: '2026-06-03',
    assignedWorkCenter: 'ASY-02',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24028',
    orderNumber: 'MO-24028',
    partNumber: 'YF-2217-C',
    partName: 'Formed frame insert',
    plannedQuantity: 750,
    completedQuantity: 750,
    scrapQuantity: 12,
    status: 'completed',
    priority: 'normal',
    dueDate: '2026-06-01',
    assignedWorkCenter: 'PRS-04',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24029',
    orderNumber: 'MO-24029',
    partNumber: 'YW-5520-D',
    partName: 'Welded support post',
    plannedQuantity: 420,
    completedQuantity: 188,
    scrapQuantity: 4,
    status: 'running',
    priority: 'high',
    dueDate: '2026-06-05',
    assignedWorkCenter: 'RB-01',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24030',
    orderNumber: 'MO-24030',
    partNumber: 'YP-7702-A',
    partName: 'Packaging spacer kit',
    plannedQuantity: 1600,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'planned',
    priority: 'low',
    dueDate: '2026-06-16',
    assignedWorkCenter: 'PKG-01',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24031',
    orderNumber: 'MO-24031',
    partNumber: 'YT-6309-B',
    partName: 'Calibration test fixture',
    plannedQuantity: 96,
    completedQuantity: 44,
    scrapQuantity: 1,
    status: 'paused',
    priority: 'expedite',
    dueDate: '2026-06-02',
    assignedWorkCenter: 'TST-01',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
  {
    id: 'po-24032',
    orderNumber: 'MO-24032',
    partNumber: 'YC-2200-F',
    partName: 'Control cabinet bracket',
    plannedQuantity: 300,
    completedQuantity: 300,
    scrapQuantity: 2,
    status: 'completed',
    priority: 'normal',
    dueDate: '2026-05-31',
    assignedWorkCenter: 'CNC-03',
    plannedShifts: [],
    manufacturingType: 'multi-step',
    productionFlow: 'standard-assembly-flow',
    assignedStation: '',
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-heat-01',
    name: 'Apex Heat Treat',
    contactName: 'Maya Chen',
    email: 'maya.chen@apexheattreat.example',
    phone: '+1 (555) 018-2401',
    address: '420 Industrial Loop, Fort Worth, TX',
    approvedStatus: 'approved',
    processCapabilities: ['Heat treatment', 'Hardness testing', 'Certification'],
    notes: 'Preferred supplier for hardened brackets and precision fixtures.',
  },
  {
    id: 'sup-coat-02',
    name: 'Northline Coatings',
    contactName: 'Daniel Ortiz',
    email: 'daniel.ortiz@northlinecoatings.example',
    phone: '+1 (555) 018-7420',
    address: '88 Powder Coat Way, Monterrey, NL',
    approvedStatus: 'approved',
    processCapabilities: ['Powder coating', 'E-coat', 'Packing slips'],
    notes: 'Good turnaround on urgent coating batches.',
  },
  {
    id: 'sup-lab-03',
    name: 'Vector Lab Services',
    contactName: 'Priya Raman',
    email: 'priya.raman@vectorlab.example',
    phone: '+1 (555) 018-1188',
    address: '12 Quality Park, Austin, TX',
    approvedStatus: 'pending-approval',
    processCapabilities: ['Lab testing', 'Material reports', 'Dimensional inspection'],
    notes: 'Pending final approval after first PPAP support run.',
  },
  {
    id: 'sup-plate-04',
    name: 'BrightArc Plating',
    contactName: 'Luis Herrera',
    email: 'luis.herrera@brightarc.example',
    phone: '+1 (555) 018-6624',
    address: '305 Finishing Ave, Saltillo, COA',
    approvedStatus: 'inactive',
    processCapabilities: ['Zinc plating', 'Black oxide', 'Passivation'],
    notes: 'Inactive until renewed quality agreement is received.',
  },
];

export const mockSupplierTransfers: SupplierTransfer[] = [
  {
    id: 'ST-260615-001',
    productionOrder: 'MO-24018',
    supplierId: 'sup-heat-01',
    supplierName: 'Apex Heat Treat',
    externalProcess: 'Heat treatment',
    partNumber: 'YW-1482-A',
    lotSerial: 'LOT-HT-24018-07',
    quantitySent: 120,
    quantityReceived: 0,
    quantityAccepted: 0,
    quantityRejected: 0,
    status: 'sent-to-supplier',
    expectedReturnDate: '2026-06-18',
    requiredDocuments: ['certificate', 'process-report'],
    receivedDocuments: [],
    documents: [],
    vouchers: [
      {
        id: 'OV-260615-001',
        transferId: 'ST-260615-001',
        direction: 'outbound',
        supplier: 'Apex Heat Treat',
        productionOrder: 'MO-24018',
        partNumber: 'YW-1482-A',
        lotSerial: 'LOT-HT-24018-07',
        quantitySent: 120,
        externalProcess: 'Heat treatment',
        checkoutDate: '2026-06-15T14:40:00.000Z',
        checkedOutBy: 'MES Supervisor',
        expectedReturnDate: '2026-06-18',
        notes: 'Priority batch for welded actuator brackets.',
      },
    ],
    notes: 'Use controlled atmosphere process and include hardness certificate.',
    checkoutNotes: 'Packed in two sealed bins.',
    receivedNotes: '',
    createdAt: '2026-06-15T13:20:00.000Z',
    updatedAt: '2026-06-15T14:40:00.000Z',
  },
  {
    id: 'ST-260612-004',
    productionOrder: 'MO-24021',
    supplierId: 'sup-coat-02',
    supplierName: 'Northline Coatings',
    externalProcess: 'Powder coating',
    partNumber: 'YA-3309-C',
    lotSerial: 'SER-3309-C-201-260',
    quantitySent: 60,
    quantityReceived: 60,
    quantityAccepted: 58,
    quantityRejected: 2,
    status: 'documents-pending',
    expectedReturnDate: '2026-06-15',
    requiredDocuments: ['inspection-report', 'packing-slip'],
    receivedDocuments: ['packing-slip'],
    documents: [
      {
        id: 'SD-260615-004-A',
        transferId: 'ST-260612-004',
        supplier: 'Northline Coatings',
        documentType: 'packing-slip',
        fileName: 'northline-packing-slip-ST-260612-004.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Receiving',
        uploadedAt: '2026-06-15T16:12:00.000Z',
        approvalStatus: 'approved',
        hash: 'sha256:demo-8f29a4',
      },
    ],
    vouchers: [
      {
        id: 'OV-260612-004',
        transferId: 'ST-260612-004',
        direction: 'outbound',
        supplier: 'Northline Coatings',
        productionOrder: 'MO-24021',
        partNumber: 'YA-3309-C',
        lotSerial: 'SER-3309-C-201-260',
        quantitySent: 60,
        externalProcess: 'Powder coating',
        checkoutDate: '2026-06-12T17:30:00.000Z',
        checkedOutBy: 'MES Supervisor',
        expectedReturnDate: '2026-06-15',
        notes: 'Mask machined surfaces per drawing note 7.',
      },
      {
        id: 'IV-260615-004',
        transferId: 'ST-260612-004',
        direction: 'inbound',
        supplier: 'Northline Coatings',
        productionOrder: 'MO-24021',
        partNumber: 'YA-3309-C',
        lotSerial: 'SER-3309-C-201-260',
        quantitySent: 60,
        quantityReceived: 60,
        quantityAccepted: 58,
        quantityRejected: 2,
        externalProcess: 'Powder coating',
        receivedDate: '2026-06-15T16:08:00.000Z',
        receivedBy: 'Receiving',
        expectedReturnDate: '2026-06-15',
        documentsReceived: ['packing-slip'],
        notes: 'Two pieces rejected for coating thickness variation.',
      },
    ],
    notes: 'Inspection report still required before closing.',
    checkoutNotes: 'Supplier pickup at dock 2.',
    receivedNotes: 'Two pieces tagged for MRB review.',
    createdAt: '2026-06-12T16:45:00.000Z',
    updatedAt: '2026-06-15T16:12:00.000Z',
  },
  {
    id: 'ST-260616-002',
    productionOrder: 'MO-24026',
    supplierId: 'sup-lab-03',
    supplierName: 'Vector Lab Services',
    externalProcess: 'Material lab testing',
    partNumber: 'YH-1840-B',
    lotSerial: 'LOT-LAB-1840-02',
    quantitySent: 12,
    quantityReceived: 0,
    quantityAccepted: 0,
    quantityRejected: 0,
    status: 'ready-for-checkout',
    expectedReturnDate: '2026-06-21',
    requiredDocuments: ['certificate', 'inspection-report'],
    receivedDocuments: [],
    documents: [],
    vouchers: [],
    notes: 'Send representative pieces for material confirmation.',
    checkoutNotes: '',
    receivedNotes: '',
    createdAt: '2026-06-16T09:10:00.000Z',
    updatedAt: '2026-06-16T09:10:00.000Z',
  },
  {
    id: 'ST-260610-003',
    productionOrder: 'MO-24024',
    supplierId: 'sup-plate-04',
    supplierName: 'BrightArc Plating',
    externalProcess: 'Black oxide',
    partNumber: 'YC-9004-D',
    lotSerial: 'LOT-BO-9004-12',
    quantitySent: 80,
    quantityReceived: 76,
    quantityAccepted: 74,
    quantityRejected: 2,
    status: 'discrepancy',
    expectedReturnDate: '2026-06-14',
    requiredDocuments: ['certificate', 'packing-slip'],
    receivedDocuments: ['certificate', 'packing-slip'],
    documents: [
      {
        id: 'SD-260614-003-A',
        transferId: 'ST-260610-003',
        supplier: 'BrightArc Plating',
        documentType: 'certificate',
        fileName: 'brightarc-black-oxide-cert-ST-260610-003.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Quality',
        uploadedAt: '2026-06-14T15:22:00.000Z',
        approvalStatus: 'pending-review',
        hash: 'sha256:demo-14b93c',
      },
      {
        id: 'SD-260614-003-B',
        transferId: 'ST-260610-003',
        supplier: 'BrightArc Plating',
        documentType: 'packing-slip',
        fileName: 'brightarc-packing-slip-ST-260610-003.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Receiving',
        uploadedAt: '2026-06-14T15:24:00.000Z',
        approvalStatus: 'approved',
      },
    ],
    vouchers: [
      {
        id: 'OV-260610-003',
        transferId: 'ST-260610-003',
        direction: 'outbound',
        supplier: 'BrightArc Plating',
        productionOrder: 'MO-24024',
        partNumber: 'YC-9004-D',
        lotSerial: 'LOT-BO-9004-12',
        quantitySent: 80,
        externalProcess: 'Black oxide',
        checkoutDate: '2026-06-10T11:18:00.000Z',
        checkedOutBy: 'MES Supervisor',
        expectedReturnDate: '2026-06-14',
        notes: 'Keep lot segregated for control enclosure kit.',
      },
      {
        id: 'IV-260614-003',
        transferId: 'ST-260610-003',
        direction: 'inbound',
        supplier: 'BrightArc Plating',
        productionOrder: 'MO-24024',
        partNumber: 'YC-9004-D',
        lotSerial: 'LOT-BO-9004-12',
        quantitySent: 80,
        quantityReceived: 76,
        quantityAccepted: 74,
        quantityRejected: 2,
        externalProcess: 'Black oxide',
        receivedDate: '2026-06-14T15:15:00.000Z',
        receivedBy: 'Receiving',
        expectedReturnDate: '2026-06-14',
        documentsReceived: ['certificate', 'packing-slip'],
        notes: 'Four pieces missing from return shipment.',
      },
    ],
    notes: 'Quantity discrepancy requires supplier corrective response.',
    checkoutNotes: 'Sent with QA seal 39021.',
    receivedNotes: 'Missing quantity and rejected pieces logged.',
    createdAt: '2026-06-10T10:55:00.000Z',
    updatedAt: '2026-06-14T15:24:00.000Z',
  },
  {
    id: 'ST-260528-005',
    productionOrder: 'MO-24028',
    supplierId: 'sup-heat-01',
    supplierName: 'Apex Heat Treat',
    externalProcess: 'Hardness testing',
    partNumber: 'YF-2217-C',
    lotSerial: 'LOT-HT-2217-05',
    quantitySent: 45,
    quantityReceived: 45,
    quantityAccepted: 45,
    quantityRejected: 0,
    status: 'completed',
    expectedReturnDate: '2026-05-31',
    requiredDocuments: ['certificate', 'process-report'],
    receivedDocuments: ['certificate', 'process-report'],
    documents: [
      {
        id: 'SD-260531-005-A',
        transferId: 'ST-260528-005',
        supplier: 'Apex Heat Treat',
        documentType: 'certificate',
        fileName: 'apex-hardness-cert-ST-260528-005.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Quality',
        uploadedAt: '2026-05-31T13:42:00.000Z',
        approvalStatus: 'approved',
      },
      {
        id: 'SD-260531-005-B',
        transferId: 'ST-260528-005',
        supplier: 'Apex Heat Treat',
        documentType: 'process-report',
        fileName: 'apex-process-report-ST-260528-005.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Quality',
        uploadedAt: '2026-05-31T13:45:00.000Z',
        approvalStatus: 'approved',
      },
    ],
    vouchers: [
      {
        id: 'OV-260528-005',
        transferId: 'ST-260528-005',
        direction: 'outbound',
        supplier: 'Apex Heat Treat',
        productionOrder: 'MO-24028',
        partNumber: 'YF-2217-C',
        lotSerial: 'LOT-HT-2217-05',
        quantitySent: 45,
        externalProcess: 'Hardness testing',
        checkoutDate: '2026-05-28T08:25:00.000Z',
        checkedOutBy: 'MES Supervisor',
        expectedReturnDate: '2026-05-31',
        notes: 'Historical hardness verification batch.',
      },
      {
        id: 'IV-260531-005',
        transferId: 'ST-260528-005',
        direction: 'inbound',
        supplier: 'Apex Heat Treat',
        productionOrder: 'MO-24028',
        partNumber: 'YF-2217-C',
        lotSerial: 'LOT-HT-2217-05',
        quantitySent: 45,
        quantityReceived: 45,
        quantityAccepted: 45,
        quantityRejected: 0,
        externalProcess: 'Hardness testing',
        receivedDate: '2026-05-31T13:38:00.000Z',
        receivedBy: 'Receiving',
        expectedReturnDate: '2026-05-31',
        documentsReceived: ['certificate', 'process-report'],
        notes: 'Closed with all documents approved.',
      },
    ],
    notes: 'Completed historical transfer retained for document lookup.',
    checkoutNotes: 'Delivered by courier.',
    receivedNotes: 'All parts accepted.',
    createdAt: '2026-05-28T08:10:00.000Z',
    updatedAt: '2026-05-31T13:45:00.000Z',
  },
  {
    id: 'ST-260503-006',
    productionOrder: 'MO-24028',
    supplierId: 'sup-coat-02',
    supplierName: 'Northline Coatings',
    externalProcess: 'E-coat',
    partNumber: 'YF-2217-C',
    lotSerial: 'SER-2217-C-118-160',
    quantitySent: 160,
    quantityReceived: 160,
    quantityAccepted: 158,
    quantityRejected: 2,
    status: 'completed',
    expectedReturnDate: '2026-05-08',
    requiredDocuments: ['inspection-report', 'packing-slip'],
    receivedDocuments: ['inspection-report', 'packing-slip'],
    documents: [
      {
        id: 'SD-260508-006-A',
        transferId: 'ST-260503-006',
        supplier: 'Northline Coatings',
        documentType: 'inspection-report',
        fileName: 'northline-inspection-report-ST-260503-006.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Quality',
        uploadedAt: '2026-05-08T18:18:00.000Z',
        approvalStatus: 'approved',
      },
      {
        id: 'SD-260508-006-B',
        transferId: 'ST-260503-006',
        supplier: 'Northline Coatings',
        documentType: 'packing-slip',
        fileName: 'northline-packing-slip-ST-260503-006.pdf',
        fileUrl: '/assets/supplier-documents/sample-supplier-document.pdf',
        uploadedBy: 'Receiving',
        uploadedAt: '2026-05-08T18:20:00.000Z',
        approvalStatus: 'approved',
      },
    ],
    vouchers: [
      {
        id: 'OV-260503-006',
        transferId: 'ST-260503-006',
        direction: 'outbound',
        supplier: 'Northline Coatings',
        productionOrder: 'MO-24028',
        partNumber: 'YF-2217-C',
        lotSerial: 'SER-2217-C-118-160',
        quantitySent: 160,
        externalProcess: 'E-coat',
        checkoutDate: '2026-05-03T15:05:00.000Z',
        checkedOutBy: 'MES Supervisor',
        expectedReturnDate: '2026-05-08',
        notes: 'Historical E-coat run for enclosure brackets.',
      },
      {
        id: 'IV-260508-006',
        transferId: 'ST-260503-006',
        direction: 'inbound',
        supplier: 'Northline Coatings',
        productionOrder: 'MO-24028',
        partNumber: 'YF-2217-C',
        lotSerial: 'SER-2217-C-118-160',
        quantitySent: 160,
        quantityReceived: 160,
        quantityAccepted: 158,
        quantityRejected: 2,
        externalProcess: 'E-coat',
        receivedDate: '2026-05-08T18:12:00.000Z',
        receivedBy: 'Receiving',
        expectedReturnDate: '2026-05-08',
        documentsReceived: ['inspection-report', 'packing-slip'],
        notes: 'Two parts accepted under deviation record.',
      },
    ],
    notes: 'Completed historical coating transfer with voucher set.',
    checkoutNotes: 'Sent in returnable racks.',
    receivedNotes: 'Deviation linked in inspection report.',
    createdAt: '2026-05-03T14:50:00.000Z',
    updatedAt: '2026-05-08T18:20:00.000Z',
  },
];

export const mockTraceabilityEvents: TraceabilityEvent[] = [
  {
    id: 'evt-1001',
    timestamp: '2026-06-01T07:12:00-07:00',
    eventType: 'order-released',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 0,
    operator: 'M. Torres',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'Released to robot weld cell with fixture set WLD-14.',
  },
  {
    id: 'evt-1002',
    timestamp: '2026-06-01T07:28:00-07:00',
    eventType: 'order-started',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 0,
    operator: 'J. Singh',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'First piece approved and cycle counter reset.',
  },
  {
    id: 'evt-1003',
    timestamp: '2026-06-01T09:05:00-07:00',
    eventType: 'production-reported',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 240,
    operator: 'J. Singh',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'Auto count accepted from cell PLC.',
  },
  {
    id: 'evt-1004',
    timestamp: '2026-06-01T09:38:00-07:00',
    eventType: 'scrap-reported',
    productionOrder: 'MO-24022',
    workCenter: 'PRS-04',
    quantity: 8,
    operator: 'A. Rivera',
    serialNumber: null,
    lotNumber: 'LOT-0601-P',
    partNumber: 'YP-2201-B',
    notes: 'Scrap reason: edge deformation after sensor fault.',
  },
  {
    id: 'evt-1005',
    timestamp: '2026-06-01T10:16:00-07:00',
    eventType: 'production-reported',
    productionOrder: 'MO-24021',
    workCenter: 'ASY-02',
    quantity: 96,
    operator: 'N. Chen',
    serialNumber: 'SN-24021-0096',
    lotNumber: 'LOT-0601-C',
    partNumber: 'YA-3309-C',
    notes: 'Assembly batch moved to end-of-line queue.',
  },
  {
    id: 'evt-1006',
    timestamp: '2026-06-01T10:42:00-07:00',
    eventType: 'quality-check',
    productionOrder: 'MO-24021',
    workCenter: 'TST-01',
    quantity: 20,
    operator: 'K. Patel',
    serialNumber: 'SN-24021-0108',
    lotNumber: 'LOT-0601-C',
    partNumber: 'YA-3309-C',
    notes: 'Functional test sample passed. Torque readings in range.',
  },
  {
    id: 'evt-1007',
    timestamp: '2026-06-01T11:03:00-07:00',
    eventType: 'work-center-change',
    productionOrder: 'MO-24022',
    workCenter: 'PRS-04',
    quantity: 0,
    operator: 'Maintenance',
    serialNumber: null,
    lotNumber: 'LOT-0601-P',
    partNumber: 'YP-2201-B',
    notes: 'Work center set to down. Order paused pending sensor replacement.',
  },
];
