import type { ProductionOrder, TraceabilityEvent, WorkCenter } from './mesTypes';

export const mockWorkCenters: WorkCenter[] = [
  {
    id: 'wc-robot-01',
    code: 'RB-01',
    name: 'Robot Weld Cell 01',
    type: 'Robotic welding cell',
    status: 'running',
    currentOrder: 'MO-24018',
    capacityPerHour: 42,
    location: 'Line A / Bay 2',
    lastActivity: 'Production reported 18 min ago',
  },
  {
    id: 'wc-cnc-03',
    code: 'CNC-03',
    name: 'CNC Machining Center 03',
    type: 'Machining center',
    status: 'available',
    currentOrder: null,
    capacityPerHour: 28,
    location: 'Machining / Cell 3',
    lastActivity: 'Order MO-24015 completed 46 min ago',
  },
  {
    id: 'wc-assy-02',
    code: 'ASY-02',
    name: 'Final Assembly Station 02',
    type: 'Manual assembly',
    status: 'running',
    currentOrder: 'MO-24021',
    capacityPerHour: 65,
    location: 'Assembly / Line B',
    lastActivity: 'Operator login 9 min ago',
  },
  {
    id: 'wc-test-01',
    code: 'TST-01',
    name: 'End-of-Line Test Stand',
    type: 'Functional test',
    status: 'maintenance',
    currentOrder: null,
    capacityPerHour: 36,
    location: 'Quality / Test Area',
    lastActivity: 'Preventive maintenance started 32 min ago',
  },
  {
    id: 'wc-pack-01',
    code: 'PKG-01',
    name: 'Packaging Cell 01',
    type: 'Packaging',
    status: 'offline',
    currentOrder: null,
    capacityPerHour: 90,
    location: 'Shipping / Dock 1',
    lastActivity: 'Offline after shift close',
  },
  {
    id: 'wc-press-04',
    code: 'PRS-04',
    name: 'Hydraulic Press 04',
    type: 'Forming press',
    status: 'down',
    currentOrder: 'MO-24022',
    capacityPerHour: 54,
    location: 'Stamping / Bay 4',
    lastActivity: 'Downtime reason: sensor fault',
  },
];

export const mockProductionOrders: ProductionOrder[] = [
  {
    id: 'po-24018',
    orderNumber: 'MO-24018',
    partNumber: 'YW-1482-A',
    partName: 'Welded actuator bracket',
    plannedQuantity: 1200,
    completedQuantity: 684,
    scrapQuantity: 11,
    status: 'running',
    priority: 'high',
    dueDate: '2026-06-04',
    assignedWorkCenter: 'RB-01',
  },
  {
    id: 'po-24021',
    orderNumber: 'MO-24021',
    partNumber: 'YA-3309-C',
    partName: 'Valve manifold assembly',
    plannedQuantity: 500,
    completedQuantity: 216,
    scrapQuantity: 3,
    status: 'running',
    priority: 'expedite',
    dueDate: '2026-06-02',
    assignedWorkCenter: 'ASY-02',
  },
  {
    id: 'po-24022',
    orderNumber: 'MO-24022',
    partNumber: 'YP-2201-B',
    partName: 'Pressed motor cover',
    plannedQuantity: 900,
    completedQuantity: 102,
    scrapQuantity: 18,
    status: 'paused',
    priority: 'normal',
    dueDate: '2026-06-07',
    assignedWorkCenter: 'PRS-04',
  },
  {
    id: 'po-24024',
    orderNumber: 'MO-24024',
    partNumber: 'YC-9004-D',
    partName: 'Control enclosure kit',
    plannedQuantity: 180,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'released',
    priority: 'normal',
    dueDate: '2026-06-10',
    assignedWorkCenter: 'CNC-03',
  },
  {
    id: 'po-24025',
    orderNumber: 'MO-24025',
    partNumber: 'YT-5110-A',
    partName: 'Tested harness set',
    plannedQuantity: 320,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'planned',
    priority: 'low',
    dueDate: '2026-06-14',
    assignedWorkCenter: 'TST-01',
  },
  {
    id: 'po-24026',
    orderNumber: 'MO-24026',
    partNumber: 'YH-1840-B',
    partName: 'Hydraulic clamp body',
    plannedQuantity: 640,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'released',
    priority: 'high',
    dueDate: '2026-06-06',
    assignedWorkCenter: 'CNC-03',
  },
  {
    id: 'po-24027',
    orderNumber: 'MO-24027',
    partNumber: 'YS-4108-A',
    partName: 'Sensor mounting rail',
    plannedQuantity: 1100,
    completedQuantity: 928,
    scrapQuantity: 7,
    status: 'running',
    priority: 'normal',
    dueDate: '2026-06-03',
    assignedWorkCenter: 'ASY-02',
  },
  {
    id: 'po-24028',
    orderNumber: 'MO-24028',
    partNumber: 'YF-2217-C',
    partName: 'Formed frame insert',
    plannedQuantity: 750,
    completedQuantity: 750,
    scrapQuantity: 12,
    status: 'completed',
    priority: 'normal',
    dueDate: '2026-06-01',
    assignedWorkCenter: 'PRS-04',
  },
  {
    id: 'po-24029',
    orderNumber: 'MO-24029',
    partNumber: 'YW-5520-D',
    partName: 'Welded support post',
    plannedQuantity: 420,
    completedQuantity: 188,
    scrapQuantity: 4,
    status: 'running',
    priority: 'high',
    dueDate: '2026-06-05',
    assignedWorkCenter: 'RB-01',
  },
  {
    id: 'po-24030',
    orderNumber: 'MO-24030',
    partNumber: 'YP-7702-A',
    partName: 'Packaging spacer kit',
    plannedQuantity: 1600,
    completedQuantity: 0,
    scrapQuantity: 0,
    status: 'planned',
    priority: 'low',
    dueDate: '2026-06-16',
    assignedWorkCenter: 'PKG-01',
  },
  {
    id: 'po-24031',
    orderNumber: 'MO-24031',
    partNumber: 'YT-6309-B',
    partName: 'Calibration test fixture',
    plannedQuantity: 96,
    completedQuantity: 44,
    scrapQuantity: 1,
    status: 'paused',
    priority: 'expedite',
    dueDate: '2026-06-02',
    assignedWorkCenter: 'TST-01',
  },
  {
    id: 'po-24032',
    orderNumber: 'MO-24032',
    partNumber: 'YC-2200-F',
    partName: 'Control cabinet bracket',
    plannedQuantity: 300,
    completedQuantity: 300,
    scrapQuantity: 2,
    status: 'completed',
    priority: 'normal',
    dueDate: '2026-05-31',
    assignedWorkCenter: 'CNC-03',
  },
];

export const mockTraceabilityEvents: TraceabilityEvent[] = [
  {
    id: 'evt-1001',
    timestamp: '2026-06-01T07:12:00-07:00',
    eventType: 'order-released',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 0,
    operator: 'M. Torres',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'Released to robot weld cell with fixture set WLD-14.',
  },
  {
    id: 'evt-1002',
    timestamp: '2026-06-01T07:28:00-07:00',
    eventType: 'order-started',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 0,
    operator: 'J. Singh',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'First piece approved and cycle counter reset.',
  },
  {
    id: 'evt-1003',
    timestamp: '2026-06-01T09:05:00-07:00',
    eventType: 'production-reported',
    productionOrder: 'MO-24018',
    workCenter: 'RB-01',
    quantity: 240,
    operator: 'J. Singh',
    serialNumber: null,
    lotNumber: 'LOT-0601-A',
    partNumber: 'YW-1482-A',
    notes: 'Auto count accepted from cell PLC.',
  },
  {
    id: 'evt-1004',
    timestamp: '2026-06-01T09:38:00-07:00',
    eventType: 'scrap-reported',
    productionOrder: 'MO-24022',
    workCenter: 'PRS-04',
    quantity: 8,
    operator: 'A. Rivera',
    serialNumber: null,
    lotNumber: 'LOT-0601-P',
    partNumber: 'YP-2201-B',
    notes: 'Scrap reason: edge deformation after sensor fault.',
  },
  {
    id: 'evt-1005',
    timestamp: '2026-06-01T10:16:00-07:00',
    eventType: 'production-reported',
    productionOrder: 'MO-24021',
    workCenter: 'ASY-02',
    quantity: 96,
    operator: 'N. Chen',
    serialNumber: 'SN-24021-0096',
    lotNumber: 'LOT-0601-C',
    partNumber: 'YA-3309-C',
    notes: 'Assembly batch moved to end-of-line queue.',
  },
  {
    id: 'evt-1006',
    timestamp: '2026-06-01T10:42:00-07:00',
    eventType: 'quality-check',
    productionOrder: 'MO-24021',
    workCenter: 'TST-01',
    quantity: 20,
    operator: 'K. Patel',
    serialNumber: 'SN-24021-0108',
    lotNumber: 'LOT-0601-C',
    partNumber: 'YA-3309-C',
    notes: 'Functional test sample passed. Torque readings in range.',
  },
  {
    id: 'evt-1007',
    timestamp: '2026-06-01T11:03:00-07:00',
    eventType: 'work-center-change',
    productionOrder: 'MO-24022',
    workCenter: 'PRS-04',
    quantity: 0,
    operator: 'Maintenance',
    serialNumber: null,
    lotNumber: 'LOT-0601-P',
    partNumber: 'YP-2201-B',
    notes: 'Work center set to down. Order paused pending sensor replacement.',
  },
];
