export type ServiceHistory = 'first_time' | 'existing_program' | 'program_modification' | 'inspection_required';
export type QuotationItemCategory = 'one_time_engineering' | 'recurring_service' | 'coating' | 'damage_surcharge' | 'addon' | 'logistics' | 'other';
export type QuotationPricingType = 'fixed' | 'hourly' | 'quantity' | 'calculated';
export type QuotationProgramStatus = 'Not created' | 'In development' | 'Validated' | 'Requires review' | 'Obsolete';
export type QuotationItem = { id:string; category:QuotationItemCategory; addonCategory?:string; pricingType:QuotationPricingType; name:string; description:string; quantity:number; unit:string; hours:number; unitPrice:number; hourlyRate:number; internalCost:number; subtotal:number; sortOrder:number; isOptional:boolean; isSelected:boolean; isRecurring:boolean; isCustomerVisible:boolean; notes:string; sourceReferenceId?:string };
export type QuotationTotals = { oneTimeEngineeringSubtotal:number; recurringServiceSubtotal:number; coatingSubtotal:number; damageSurchargeSubtotal:number; addonsSubtotal:number; otherSubtotal:number; quotationTotal:number; estimatedFutureRepeatPrice:number };
export const serviceHistoryOptions = [
  {value:'first_time' as const,label:'First-time tool / New tool setup'}, {value:'existing_program' as const,label:'Existing validated program'},
  {value:'program_modification' as const,label:'Existing program requires modification'}, {value:'inspection_required' as const,label:'Inspection required before final quotation'},
];
const item = (category:QuotationItemCategory,name:string,rate:number,order:number):QuotationItem => ({id:crypto.randomUUID(),category,pricingType:'hourly',name,description:name,quantity:1,unit:'hour',hours:0,hourlyRate:rate,unitPrice:0,internalCost:0,subtotal:0,sortOrder:order,isOptional:false,isSelected:true,isRecurring:category==='recurring_service',isCustomerVisible:true,notes:''});
export const engineeringDefaults = (rate:number) => ['Initial dimensional measurement','Geometry analysis','Sharpening program development','Measurement program development','Machine setup and trial','Process validation'].map((name,index)=>item('one_time_engineering',name,rate,index));
export const recurringDefaults = (rate:number) => ['Program retrieval and verification','Machine setup','Sharpening','Final measurement / inspection','Cleaning and handling'].map((name,index)=>item('recurring_service',name,rate,index));
export function recalculateItem(value:QuotationItem):QuotationItem { const subtotal=value.pricingType==='hourly'?value.hours*value.hourlyRate:value.pricingType==='quantity'?value.quantity*value.unitPrice:value.unitPrice; return {...value,subtotal:Math.round(subtotal*100)/100}; }
export function calculateQuotationTotals(items:QuotationItem[],coating:number,damage:number):QuotationTotals { const included=items.filter(i=>i.isSelected||!i.isOptional).map(recalculateItem); const sum=(category:QuotationItemCategory)=>included.filter(i=>i.category===category).reduce((n,i)=>n+i.subtotal,0); const oneTimeEngineeringSubtotal=sum('one_time_engineering'), recurringServiceSubtotal=sum('recurring_service'), addonsSubtotal=sum('addon'), otherSubtotal=sum('other')+sum('logistics'); const recurringAddons=included.filter(i=>i.category==='addon'&&i.isRecurring).reduce((n,i)=>n+i.subtotal,0); return {oneTimeEngineeringSubtotal,recurringServiceSubtotal,coatingSubtotal:coating,damageSurchargeSubtotal:damage,addonsSubtotal,otherSubtotal,quotationTotal:oneTimeEngineeringSubtotal+recurringServiceSubtotal+coating+damage+addonsSubtotal+otherSubtotal,estimatedFutureRepeatPrice:recurringServiceSubtotal+coating+damage+recurringAddons}; }
export function legacyRecurringItem(minutes:number,rate:number):QuotationItem { return {...item('recurring_service','Sharpening',rate,2),hours:minutes/60,subtotal:minutes/60*rate}; }
