import React from 'react';
import { AlertTriangle, ArrowLeft, CalendarDays, CircleDollarSign, Clock3, Factory, Gauge, RefreshCw, TrendingUp } from 'lucide-react';
import { supabase } from '../lib/supabaseClient';
import { useSupabaseRealtimeRefresh } from '../lib/useSupabaseRealtimeRefresh';
import './revenueOpportunity.css';

type Props = { onNavigate: (path: string) => void; organizationId: string; activeSection: 'price-misalignment' | 'optimization' };
type SerialRow = { id: string; production_order_id: string; reported_at: string; mes_production_orders: { order_number: string; assigned_work_center: string; client_name: string } | null; mes_legacy_prices: { price: number; currency: string } | null; mes_quotations: { total_price: number; currency: string | null } | null };
type CycleRow = { id: string; work_center_code: string; station_code: string; status: string; started_at: string; ended_at: string | null };
type CenterRow = { code: string; name: string };
type RangePreset = 'current' | 'previous' | 'custom';

const money = (value: number, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value || 0);
const pct = (value: number) => `${Number.isFinite(value) ? value.toFixed(1) : '0.0'}%`;
const dateInput = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const monthRange = (offset = 0) => { const now = new Date(); const from = new Date(now.getFullYear(), now.getMonth() + offset, 1); const to = new Date(now.getFullYear(), now.getMonth() + offset + 1, 0); return { from: dateInput(from), to: dateInput(to) }; };
const relation = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] ?? null : value;

export function RevenueOpportunityWorkspace({ onNavigate, organizationId, activeSection }: Props) {
  const initial = React.useMemo(() => monthRange(), []);
  const [preset, setPreset] = React.useState<RangePreset>('current');
  const [range, setRange] = React.useState(initial);
  const [serials, setSerials] = React.useState<SerialRow[]>([]);
  const [cycles, setCycles] = React.useState<CycleRow[]>([]);
  const [centers, setCenters] = React.useState<CenterRow[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState('');
  const [updatedAt, setUpdatedAt] = React.useState('');
  const [idleRecovery, setIdleRecovery] = React.useState(50);
  const [downtimeRecovery, setDowntimeRecovery] = React.useState(30);
  const [realization, setRealization] = React.useState(70);
  const [variableCost, setVariableCost] = React.useState(0);

  const load = React.useCallback(async (silent = false) => {
    if (!silent) setLoading(true);
    const from = new Date(`${range.from}T00:00:00`).toISOString();
    const end = new Date(`${range.to}T00:00:00`); end.setDate(end.getDate() + 1); const to = end.toISOString();
    const [serialResult, cycleResult, centerResult] = await Promise.all([
      supabase.from('mes_production_serials').select('id, production_order_id, reported_at, mes_production_orders!inner(order_number, assigned_work_center, client_name), mes_legacy_prices(price, currency), mes_quotations(total_price, currency)').eq('organization_id', organizationId).eq('result', 'good').gte('reported_at', from).lt('reported_at', to),
      supabase.from('mes_station_status_cycles').select('id, work_center_code, station_code, status, started_at, ended_at').eq('organization_id', organizationId).lt('started_at', to).or(`ended_at.is.null,ended_at.gt.${from}`),
      supabase.from('mes_work_centers').select('code, name').eq('organization_id', organizationId).order('name'),
    ]);
    const queryError = serialResult.error || cycleResult.error || centerResult.error;
    if (queryError) setError(queryError.message); else {
      setSerials((serialResult.data ?? []).map((row) => ({ ...row, mes_production_orders: relation(row.mes_production_orders), mes_legacy_prices: relation(row.mes_legacy_prices), mes_quotations: relation(row.mes_quotations) })) as unknown as SerialRow[]);
      setCycles((cycleResult.data ?? []) as CycleRow[]); setCenters((centerResult.data ?? []) as CenterRow[]); setError(''); setUpdatedAt(new Date().toISOString());
    }
    setLoading(false);
  }, [organizationId, range.from, range.to]);
  React.useEffect(() => { void load(); }, [load]);
  useSupabaseRealtimeRefresh({ channelName: `revenue-opportunity:${organizationId}`, tables: [{ table: 'mes_production_serials', filter: `organization_id=eq.${organizationId}` }, { table: 'mes_legacy_prices', filter: `organization_id=eq.${organizationId}` }, { table: 'mes_quotations', filter: `organization_id=eq.${organizationId}` }, { table: 'mes_station_status_cycles', filter: `organization_id=eq.${organizationId}` }], onRefresh: () => void load(true) });

  const analysis = React.useMemo(() => {
    const startMs = new Date(`${range.from}T00:00:00`).getTime(); const endDate = new Date(`${range.to}T00:00:00`); endDate.setDate(endDate.getDate() + 1); const endMs = Math.min(endDate.getTime(), Date.now());
    const byCenter = new Map<string, { current: number; quoted: number; comparableLegacy: number; comparableQuoted: number; pricingGap: number; overpricing: number; pieces: number; matched: number; productive: number; idle: number; downtime: number; stations: Set<string> }>();
    const getCenter = (code: string) => { const current = byCenter.get(code) ?? { current: 0, quoted: 0, comparableLegacy: 0, comparableQuoted: 0, pricingGap: 0, overpricing: 0, pieces: 0, matched: 0, productive: 0, idle: 0, downtime: 0, stations: new Set<string>() }; byCenter.set(code, current); return current; };
    serials.forEach((serial) => { const order = relation(serial.mes_production_orders); if (!order) return; const item = getCenter(order.assigned_work_center || 'Unassigned'); const legacy = relation(serial.mes_legacy_prices); const quote = relation(serial.mes_quotations); item.pieces += 1; if (legacy) item.current += Number(legacy.price) || 0; if (quote) item.quoted += Number(quote.total_price) || 0; if (legacy && quote) { const legacyValue = Number(legacy.price) || 0; const quoteValue = Number(quote.total_price) || 0; item.matched += 1; item.comparableLegacy += legacyValue; item.comparableQuoted += quoteValue; item.pricingGap += Math.max(0, quoteValue - legacyValue); item.overpricing += Math.max(0, legacyValue - quoteValue); } });
    cycles.forEach((cycle) => { const item = getCenter(cycle.work_center_code || 'Unassigned'); item.stations.add(cycle.station_code); const from = Math.max(startMs, new Date(cycle.started_at).getTime()); const to = Math.min(endMs, cycle.ended_at ? new Date(cycle.ended_at).getTime() : Date.now()); const hours = Math.max(0, to - from) / 3600000; if (cycle.status === 'running') item.productive += hours; else if (cycle.status === 'down') item.downtime += hours; else if (cycle.status === 'idle' || cycle.status === 'available') item.idle += hours; });
    const rows = [...byCenter.entries()].map(([code, data]) => { const rate = data.productive > 0 ? data.current / data.productive : 0; const pricing = data.pricingGap; const idle = data.idle * idleRecovery / 100 * rate; const downtime = data.downtime * downtimeRecovery / 100 * rate; const theoreticalGross = pricing + idle + downtime; const realisticGross = theoreticalGross * realization / 100; const cost = realisticGross * variableCost / 100; const net = realisticGross - cost; return { code, name: centers.find((center) => center.code === code)?.name ?? code, ...data, rate, pricing, idleOpportunity: idle, downtimeOpportunity: downtime, theoreticalGross, net, potential: data.current + net, uplift: data.current > 0 ? net / data.current * 100 : 0, utilization: data.productive + data.idle + data.downtime > 0 ? data.productive / (data.productive + data.idle + data.downtime) * 100 : 0 }; }).sort((a, b) => b.net - a.net);
    const total = rows.reduce((sum, row) => ({ current: sum.current + row.current, quoted: sum.quoted + row.quoted, comparableLegacy: sum.comparableLegacy + row.comparableLegacy, comparableQuoted: sum.comparableQuoted + row.comparableQuoted, pricing: sum.pricing + row.pricing, overpricing: sum.overpricing + row.overpricing, idle: sum.idle + row.idleOpportunity, downtime: sum.downtime + row.downtimeOpportunity, productive: sum.productive + row.productive, idleHours: sum.idleHours + row.idle, downtimeHours: sum.downtimeHours + row.downtime, pieces: sum.pieces + row.pieces, matched: sum.matched + row.matched }), { current: 0, quoted: 0, comparableLegacy: 0, comparableQuoted: 0, pricing: 0, overpricing: 0, idle: 0, downtime: 0, productive: 0, idleHours: 0, downtimeHours: 0, pieces: 0, matched: 0 });
    const theoreticalOpportunity = total.pricing + total.idle + total.downtime; const realisticGross = theoreticalOpportunity * realization / 100; const cost = realisticGross * variableCost / 100; const net = realisticGross - cost;
    return { rows, ...total, netPriceDifference: total.comparableQuoted - total.comparableLegacy, theoreticalOpportunity, realisticGross, cost, net, potential: total.current + net, theoreticalPotential: total.current + theoreticalOpportunity, uplift: total.current > 0 ? net / total.current * 100 : 0, coverage: total.pieces ? total.matched / total.pieces * 100 : 0, confidence: total.pieces && total.matched === total.pieces && total.productive > 0 ? 'High' : total.matched > 0 ? 'Medium' : 'Low' };
  }, [centers, cycles, downtimeRecovery, idleRecovery, range.from, range.to, realization, serials, variableCost]);
  const opportunities = [
    { name: 'Pricing alignment', value: analysis.pricing, color: '#10b981', detail: `${analysis.matched} pieces with comparable legacy and YVIMO prices`, available: analysis.matched > 0 },
    { name: 'Idle capacity', value: analysis.idle, color: '#34d399', detail: `${analysis.idleHours.toFixed(1)} idle hours × ${idleRecovery}% recovery`, available: analysis.productive > 0 },
    { name: 'Downtime recovery', value: analysis.downtime, color: '#0d9488', detail: `${analysis.downtimeHours.toFixed(1)} downtime hours × ${downtimeRecovery}% recovery`, available: analysis.productive > 0 },
    { name: 'Scheduling optimization', value: 0, color: '#65a30d', detail: 'Insufficient machine-compatibility history for a defensible estimate', available: false },
    { name: 'Additional orders', value: 0, color: '#84cc16', detail: 'Unavailable until pending-order cycle estimates are complete', available: false },
  ];
  const maxOpportunity = Math.max(1, ...opportunities.map((item) => item.value));
  const setPresetRange = (next: RangePreset) => { setPreset(next); if (next === 'current') setRange(monthRange()); if (next === 'previous') setRange(monthRange(-1)); };

  return <section className="revenue-opportunity-workspace">
    <header className="revenue-header"><button className="academy-back-button engineering-back-button mes-workspace-back revenue-back" type="button" onClick={() => onNavigate('/workspace/manufacturing-ops/intelligence')}><ArrowLeft size={16} /> Ops Intelligence</button><div className="revenue-compact-heading"><span>OPS INTELLIGENCE / FINANCE</span><h1>{activeSection === 'price-misalignment' ? 'Price Misalignment' : 'Revenue Optimization'}</h1><p>{activeSection === 'price-misalignment' ? 'Legacy vs. YVIMO pricing' : 'Operational earning potential'}</p></div><section className="revenue-controls"><div className="revenue-period-tabs">{(['current', 'previous', 'custom'] as const).map((item) => <button className={preset === item ? 'active' : ''} type="button" key={item} onClick={() => setPresetRange(item)}>{item === 'current' ? 'Current month' : item === 'previous' ? 'Previous month' : 'Custom'}</button>)}</div><label><span>From</span><input type="date" value={range.from} onChange={(event) => { setPreset('custom'); setRange((current) => ({ ...current, from: event.target.value })); }} /></label><label><span>To</span><input type="date" value={range.to} onChange={(event) => { setPreset('custom'); setRange((current) => ({ ...current, to: event.target.value })); }} /></label><button className="revenue-refresh" type="button" disabled={loading} onClick={() => void load()}><RefreshCw size={15} className={loading ? 'spinning' : ''} /> Refresh</button></section><span className="revenue-live"><span><i /> Live analysis</span><small>{updatedAt ? new Date(updatedAt).toLocaleTimeString() : 'Connecting'}</small></span></header>
    {error ? <div className="revenue-error"><AlertTriangle size={18} />{error}</div> : null}
    {activeSection === 'price-misalignment' ? <>
      <section className="revenue-kpis price-misalignment-kpis"><article><CircleDollarSign /><span><small>Actually Charged</small><strong>{money(analysis.comparableLegacy)}</strong><em>legacy price · comparable produced pieces</em></span></article><article className="potential"><CircleDollarSign /><span><small>Should Have Charged</small><strong>{money(analysis.comparableQuoted)}</strong><em>linked YVIMO source quotations</em></span></article><article className="loss"><TrendingUp /><span><small>Revenue Being Lost</small><strong>{money(analysis.pricing)}</strong><em>pieces priced below YVIMO recommendation</em></span></article><article className="over"><TrendingUp /><span><small>Revenue Above Recommendation</small><strong>{money(analysis.overpricing)}</strong><em>pieces priced above YVIMO recommendation</em></span></article><article className={analysis.netPriceDifference >= 0 ? 'loss' : 'over'}><Gauge /><span><small>Net Price Difference</small><strong>{analysis.netPriceDifference >= 0 ? '+' : '−'}{money(Math.abs(analysis.netPriceDifference))}</strong><em>{analysis.netPriceDifference >= 0 ? 'additional revenue recommended' : 'legacy revenue above recommendation'}</em></span></article></section>
      <section className="price-comparison-grid"><article className="revenue-chart-panel price-comparison-chart"><header><span><small>Commercial comparison</small><h2>Legacy vs. YVIMO recommended revenue</h2></span><strong>{analysis.matched} matched pieces · {pct(analysis.coverage)} coverage</strong></header><div className="price-paired-bars">{analysis.rows.filter((row) => row.matched > 0).map((row) => { const max = Math.max(row.comparableLegacy, row.comparableQuoted, 1); return <article key={row.code}><header><strong>{row.name}</strong><small>{row.matched} comparable pieces</small></header><div><span><i className="legacy" style={{ width: `${row.comparableLegacy / max * 100}%` }} /><b>Legacy</b><em>{money(row.comparableLegacy)}</em></span><span><i className="yvimo" style={{ width: `${row.comparableQuoted / max * 100}%` }} /><b>YVIMO</b><em>{money(row.comparableQuoted)}</em></span></div><footer className={row.comparableQuoted >= row.comparableLegacy ? 'loss' : 'gain'}>{row.comparableQuoted >= row.comparableLegacy ? `${money(row.comparableQuoted - row.comparableLegacy)} missed revenue` : `${money(row.comparableLegacy - row.comparableQuoted)} above recommendation`}</footer></article>; })}{!analysis.rows.some((row) => row.matched) ? <p className="price-empty">No produced pieces have both a Legacy Price and Source Quotation in this period.</p> : null}</div></article><aside className="price-misalignment-summary"><header><small>Price health</small><h2>What the comparison means</h2></header><div className={analysis.netPriceDifference >= 0 ? 'negative' : 'positive'}><strong>{analysis.netPriceDifference >= 0 ? 'Underpriced' : 'Above recommendation'}</strong><b>{money(Math.abs(analysis.netPriceDifference))}</b><span>net across matched pieces</span></div><dl><div><dt>Comparable pieces</dt><dd>{analysis.matched}</dd></div><div><dt>Unmatched pieces</dt><dd>{Math.max(0, analysis.pieces - analysis.matched)}</dd></div><div><dt>Price coverage</dt><dd>{pct(analysis.coverage)}</dd></div><div><dt>Comparison confidence</dt><dd>{analysis.matched && analysis.coverage === 100 ? 'High' : analysis.matched ? 'Medium' : 'Low'}</dd></div></dl><p>Only good pieces produced during the selected period with both prices are included in monetary comparisons. Unmatched pieces affect coverage, but never receive an estimated price.</p></aside></section>
      <section className="revenue-workcenters price-detail-table"><header><span><small>Price comparison detail</small><h2>Misalignment by workcenter</h2></span><span>Produced pieces only</span></header><div className="revenue-table-wrap"><table><thead><tr><th>Workcenter</th><th>Compared Pieces</th><th>Legacy Revenue</th><th>YVIMO Revenue</th><th>Revenue Lost</th><th>Above Recommendation</th><th>Net Difference</th><th>Coverage</th></tr></thead><tbody>{analysis.rows.map((row) => <tr key={row.code}><td><strong>{row.name}</strong><small>{row.code}</small></td><td>{row.matched} / {row.pieces}</td><td>{money(row.comparableLegacy)}</td><td>{money(row.comparableQuoted)}</td><td><strong className="price-loss">{money(row.pricing)}</strong></td><td><strong className="price-gain">{money(row.overpricing)}</strong></td><td><strong className={row.comparableQuoted > row.comparableLegacy ? 'price-loss' : 'price-gain'}>{row.comparableQuoted >= row.comparableLegacy ? '+' : '−'}{money(Math.abs(row.comparableQuoted - row.comparableLegacy))}</strong></td><td>{pct(row.pieces ? row.matched / row.pieces * 100 : 0)}</td></tr>)}</tbody></table></div></section>
      <section className="revenue-methodology"><CircleDollarSign size={20} /><span><strong>Strict price-comparison scope</strong><p>Actual revenue is the Legacy Price currently charged. Recommended revenue is the linked YVIMO Source Quotation. Revenue Being Lost sums only positive quote-minus-legacy differences; Revenue Above Recommendation is kept separate so favorable and unfavorable pricing do not conceal each other.</p></span><span className={`confidence ${analysis.matched && analysis.coverage === 100 ? 'high' : analysis.matched ? 'medium' : 'low'}`}>{pct(analysis.coverage)} coverage</span></section>
    </> : <>
    <section className="revenue-kpis"><article><CircleDollarSign /><span><small>Current Revenue</small><strong>{money(analysis.current)}</strong><em>legacy prices · {analysis.pieces} produced pieces</em></span></article><article className="potential"><TrendingUp /><span><small>Realistic Potential Revenue</small><strong>{money(analysis.potential)}</strong><em>recommended scenario</em></span></article><article className="opportunity"><Gauge /><span><small>Net Revenue Opportunity</small><strong>{money(analysis.net)}</strong><em>{money(analysis.theoreticalOpportunity)} theoretical gross</em></span></article><article><TrendingUp /><span><small>Potential Uplift</small><strong>{pct(analysis.uplift)}</strong><em>{analysis.confidence} confidence · {pct(analysis.coverage)} price coverage</em></span></article></section>
    <section className="revenue-main-grid"><article className="revenue-chart-panel"><header><span><small>Revenue bridge</small><h2>Current vs. potential revenue</h2></span><div><b>Realistic</b><em>Theoretical {money(analysis.theoreticalPotential)}</em></div></header><div className="revenue-bridge"><div className="revenue-bridge-scale"><span>{money(analysis.potential)}</span><span>{money(analysis.current)}</span><span>$0</span></div><div className="revenue-bridge-columns"><div><i style={{ height: `${analysis.potential ? analysis.current / analysis.potential * 100 : 0}%` }} /><strong>{money(analysis.current)}</strong><span>Current revenue</span></div><div className="gap"><i style={{ height: `${analysis.potential ? analysis.net / analysis.potential * 100 : 0}%` }} /><strong>+{money(analysis.net)}</strong><span>Net opportunity</span></div><div className="potential"><i style={{ height: '100%' }} /><strong>{money(analysis.potential)}</strong><span>Realistic potential</span></div></div></div></article><aside className="revenue-assumptions"><header><small>Scenario assumptions</small><h2>Recovery factors</h2></header>{[["Idle capacity", idleRecovery, setIdleRecovery], ["Downtime", downtimeRecovery, setDowntimeRecovery], ["Realization", realization, setRealization], ["Variable cost", variableCost, setVariableCost]].map(([label, value, setter]) => <label key={label as string}><span><b>{label as string}</b><strong>{value as number}%</strong></span><input type="range" min="0" max="100" step="5" value={value as number} onChange={(event) => (setter as React.Dispatch<React.SetStateAction<number>>)(Number(event.target.value))} /></label>)}<p>Potential Revenue uses the realistic net opportunity. No operating cost is assumed until a variable-cost factor is configured.</p></aside></section>
    <section className="revenue-opportunity-panel"><header><span><small>Opportunity decomposition</small><h2>Where the upside comes from</h2></span><strong>{money(analysis.theoreticalOpportunity)} theoretical</strong></header><div>{opportunities.map((item) => <article className={!item.available ? 'unavailable' : ''} key={item.name}><span><b>{item.name}</b><em>{item.detail}</em></span><div><i style={{ width: `${item.available ? item.value / maxOpportunity * 100 : 0}%`, background: item.color }} /></div><strong>{item.available ? money(item.value) : 'Insufficient data'}</strong></article>)}</div><footer>Gross realistic opportunity {money(analysis.realisticGross)} − Additional operating cost {money(analysis.cost)} = <strong>{money(analysis.net)} net opportunity</strong></footer></section>
    <section className="revenue-workcenters"><header><span><small>Workcenter breakdown</small><h2>Revenue opportunity by workcenter</h2></span><span>Highest impact first</span></header><div className="revenue-table-wrap"><table><thead><tr><th>Workcenter</th><th>Current Revenue</th><th>Productive / Available</th><th>Utilization</th><th>Downtime</th><th>Revenue / Hour</th><th>Main Opportunity</th><th>Potential Revenue</th><th>Uplift</th></tr></thead><tbody>{analysis.rows.map((row) => { const sources = [{ label: 'Pricing alignment', value: row.pricing }, { label: 'Idle capacity', value: row.idleOpportunity }, { label: 'Downtime', value: row.downtimeOpportunity }].sort((a, b) => b.value - a.value); return <tr key={row.code}><td><strong>{row.name}</strong><small>{row.code}</small></td><td>{money(row.current)}</td><td>{row.productive.toFixed(1)}h / {(row.productive + row.idle + row.downtime).toFixed(1)}h</td><td><span className="revenue-utilization"><i style={{ width: `${row.utilization}%` }} /></span>{pct(row.utilization)}</td><td>{row.downtime.toFixed(1)}h</td><td>{row.rate ? money(row.rate) : 'Unavailable'}</td><td><b className="revenue-source">{sources[0].value > 0 ? sources[0].label : 'Insufficient data'}</b></td><td><strong>{money(row.potential)}</strong><small>+{money(row.net)}</small></td><td><strong className="positive">{pct(row.uplift)}</strong></td></tr>; })}{!analysis.rows.length ? <tr><td colSpan={9} className="empty">{loading ? 'Loading financial production data…' : 'No produced pieces or machine activity in this period.'}</td></tr> : null}</tbody></table></div></section>
    <section className="revenue-methodology"><CalendarDays size={20} /><span><strong>Calculation scope</strong><p>Current Revenue uses legacy prices attached to good serialized pieces produced inside the selected period. Pricing Alignment compares those same pieces with their linked YVIMO quotations. Idle and downtime opportunities use observed station-cycle hours and realized revenue per productive hour. Scheduling and Additional Orders remain unavailable until the system has sufficient compatibility and cycle-estimate coverage.</p></span><span className={`confidence ${analysis.confidence.toLowerCase()}`}>{analysis.confidence} confidence</span></section>
    </>}
  </section>;
}
